import numpy as np

N = 32
j = np.arange(N)
xi = 2.0 * np.pi * (j + 0.5) / N
theta_0 = np.pi
gamma = 0.85

# Current formula:
d_xi = 0.5 * (xi - theta_0)
theta = theta_0 + 2.0 * np.arctan(gamma * np.tan(d_xi))
theta = np.mod(theta, 2.0 * np.pi)
theta = np.sort(theta)

print("Angles generated by current shock layer formula:")
print(np.round(theta, 3))
print("Min gap:", np.min(np.diff(theta)))
print("Max gap:", np.max(np.diff(theta)))
